# Generated by Django 2.1.5 on 2020-02-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200224_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
