# Generated by Django 2.1.5 on 2020-02-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20200223_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
